### ISSUE TITLE
Advisor check

### ISSUE THREAD

**Issue by tbhall** [SCCapstone/AdviseMe#119]
- [ ] Sending classes from the catalogue that it recommends to the advisor for the check off. 

- [ ]  Getting a approval/rejection from advisor on classes

**Comment by tmoon8730** [comment]
Some minor bugs are still present and there is some room for improvement but the beta release is ready to go

**Comment by parsonsbatsc** [comment]
User cart appears to function, but sending to the advisor comes back with "no data found."  It does go to the advisor, but it doesn't disappear from the list on the advisor's page after the advisor approves it.  

Also, for some reason the advisor can request classes from himself.  This could probably be fixed with a few small changes to the advisor page (like removing a couple of buttons.)

Receiving approval or rejection still appears to need implemented.

**Comment by tbhall** [comment]
@parsonsbatsc We will look into this. Thank you for pointing out this issue.

Thanks,
AdviseMe team

**Comment by tbhall** [comment]
Currently it only sends a sms notification to the static number we have on the site which is why it seemed like it wasn't doing anything. Another issue will resolve this.
